FROM osrf/ros:humble-desktop

# root user
ENV USERNAME isa
ENV HOME /home/$USERNAME

ENV NVIDIA_VISIBLE_DEVICES ${NVIDIA_VISIBLE_DEVICES:-all}
ENV NVIDIA_DRIVER_CAPABILITIES ${NVIDIA_DRIVER_CAPABILITIES:+$NVIDIA_DRIVER_CAPABILITIES,}graphics

RUN useradd -m $USERNAME && \
    echo "$USERNAME:$USERNAME" | chpasswd && \
    usermod --shell /bin/bash $USERNAME && \
    usermod -aG sudo $USERNAME && \
    mkdir -p /etc/sudoers.d && \
    echo "$USERNAME ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers.d/$USERNAME && \
    chmod 0440 /etc/sudoers.d/$USERNAME && \
    # Replace 1000 with your user/group id
    usermod --uid 1000 $USERNAME && \
    groupmod --gid 1000 $USERNAME


RUN apt-get update && \
    apt-get install -q -y --no-install-recommends \
    wget apt-utils sudo curl python3-vcstool \
    git\
    sudo \
    python3-pip \
    ipython3 \
    python3-dev \
    python3-numpy \
    python3-scipy \
    python3-matplotlib \
    python3-setuptools \
    python3-setuptools-scm \
    swig \
	&& apt-get clean -q -y \
	&& apt-get autoremove -q -y \
	&& rm -rf /var/lib/apt/lists/*

RUN apt-get update \
    && pip install --no-cache-dir fastapi uvicorn uvicorn[standard] \
    && ln -s /usr/bin/python3 /usr/bin/python 

#RUN apt-get update \
#&& python3 -m pip install --upgrade pip setuptools setuptools_scm wheel

# set python3.8 as default
# RUN sudo update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.8 1

RUN apt-get update && \
    apt-get install -y \
    cmake \
    liblapack-dev \
    libblas-dev \
    libboost-all-dev \
    libflann-dev \
    libusb-1.0-0-dev \
    libqhull-dev \
    libboost-all-dev \
    libpcl-dev \
    gcc \
    g++ \
    gfortran \
    git \
    pkg-config \
    && rm -rf /var/lib/apt/lists/*

RUN apt-get update && \ 
    apt -y install qtbase5-dev libqt5svg5-dev libqt5websockets5-dev \
    libqt5opengl5-dev libqt5x11extras5-dev libprotoc-dev libzmq3-dev \
    liblz4-dev libzstd-dev

RUN apt-get update && \
    apt-get install -y wget && \
    wget https://github.com/Kitware/CMake/releases/download/v3.21.0/cmake-3.21.0-linux-x86_64.sh && \
    chmod +x cmake-3.21.0-linux-x86_64.sh && \
    ./cmake-3.21.0-linux-x86_64.sh --skip-license --prefix=/usr/local && \
    rm cmake-3.21.0-linux-x86_64.sh

COPY ../udev/* /etc/udev/rules.d/

USER $USERNAME
WORKDIR $HOME

RUN sudo apt-get update \
&& git clone https://github.com/acados/acados.git \
&& cd acados && git submodule update --init --recursive \
&& mkdir -p build && cd build \
&& cmake .. \
&& sudo make install -j4 

RUN sudo apt-get update \
&& pip3 install -e ${HOME}/acados/interfaces/acados_template

# RUN sudo apt-get update \
# && git clone https://github.com/OctoMap/octomap.git \
# && cd $HOME/octomap/octomap \
# && mkdir build && cd build \
# && cmake .. \	
# && sudo make install -j4

# RUN sudo apt-get update \
# && cd $HOME/octomap/dynamicEDT3D \
# && mkdir build && cd build \
# && cmake .. \
# && sudo make install -j4

# RUN sudo apt-get update \
# && git clone https://github.com/facontidavide/PlotJuggler.git ~/plotjuggler_ws/src/PlotJuggler \
# && cd ~/plotjuggler_ws \
# && cmake -S src/PlotJuggler -B build/PlotJuggler -DCMAKE_INSTALL_PREFIX=install \
# && cmake --build build/PlotJuggler --config RelWithDebInfo --target install



RUN sudo apt install -y libxcb-xinerama0 libxcb-cursor0 \
&& pip3 install --upgrade pip


RUN sudo apt-get update && \
    sudo curl https://packages.osrfoundation.org/gazebo.gpg --output /usr/share/keyrings/pkgs-osrf-archive-keyring.gpg && \
    echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/pkgs-osrf-archive-keyring.gpg] http://packages.osrfoundation.org/gazebo/ubuntu-stable $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/gazebo-stable.list > /dev/null && \
    sudo apt-get update && \
    sudo apt-get install gz-garden -y

RUN sudo apt-get update && \
    git clone https://github.com/gtfactslab/CrazySim.git --recursive && \
    cd CrazySim && \
    cd crazyflie-lib-python && \
    pip3 install -e .
    
RUN sudo apt-get update && \
    cd CrazySim && \
    cd crazyflie-firmware && \
    mkdir -p sitl_make/build && cd sitl_make/build && \
    cmake .. && \
    sudo make all

RUN sudo apt-get update && \
    pip install Jinja2 

RUN sudo apt-get update \
    && git clone https://github.com/llanesc/crazyflie-clients-python \
    && cd $HOME/crazyflie-clients-python \
    && git checkout sitl-release \
    && pip3 install -e .

RUN sudo apt-get update \
    && sudo apt install ros-humble-ros-gzgarden -y 


RUN sudo apt-get update && \
    rosdep update

RUN sudo apt-get update && \
    mkdir -p $HOME/ws_plotjuggler/src && \
    cd $HOME/ws_plotjuggler/src && \
    git clone https://github.com/PlotJuggler/plotjuggler-ros-plugins.git && \
    cd plotjuggler-ros-plugins && \
    git checkout humble && \
    cd $HOME/ws_plotjuggler && \
    rosdep install --from-paths src --ignore-src --rosdistro=${ROS_DISTRO} -y 
    
RUN /bin/bash -c "echo 'source /opt/ros/humble/setup.bash' >> $HOME/.bashrc"


RUN bash -c "source /opt/ros/humble/setup.bash && \
    cd /home/isa/ws_plotjuggler && \
    colcon build --symlink-install --cmake-args -DCMAKE_BUILD_TYPE=Release && \
    echo 'source /home/isa/ws_plotjuggler/install/setup.bash' >> /home/isa/.bashrc"
    
RUN mkdir -p $HOME/catkin_ws/src
WORKDIR $HOME/catkin_ws/

# RUN sudo apt-get update && \
#     sudo apt-get install -y netbase iputils-ping telnet

ENV ACADOS_SOURCE_DIR=${HOME}/acados
ENV CASADI_SOURCE_DIR=${HOME}/casadi
ENV LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:"${CASADI_SOURCE_DIR}/build/lib"
ENV LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:"${ACADOS_SOURCE_DIR}/lib"
ENV PATH=${PATH}:${HOME}/.local/bin